# Generated by Django 3.2 on 2022-05-14 01:20

from django.db import migrations, models
import django.db.models.deletion
import rental.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(validators=[rental.models.validate_reservation_date])),
                ('checkout', models.DateField(validators=[rental.models.validate_reservation_date])),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='rental.rental')),
            ],
        ),
    ]
